spring:
  application:
    name: tensquare‐config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/a2008q/tensquare-config.git
  rabbitmq:
    host: 127.0.0.1
server:
  port: 12000

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh