server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: 127.0.0.1
      database: spit
  redis:
    host: localhost
jwt:
  config:
    key: OgM9k5oT
eureka:
  client:
    service‐url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer‐ip‐address: true #跨服务器访问
